import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { Wallet, ArrowDownRight, ArrowUpRight, Coins, RefreshCw, CreditCard, ShieldCheck, CheckCircle2, Zap } from 'lucide-react';
import { API_BASE_URL } from '../config/api';
import './ArenaWallet.css';

const ArenaWallet = () => {
  const { user, getAuthHeader } = useAuth();
  const [wallet, setWallet] = useState(null);
  const [loading, setLoading] = useState(true);
  const [depositAmount, setDepositAmount] = useState('500');
  const [withdrawAmount, setWithdrawAmount] = useState('200');
  const [upiId, setUpiId] = useState('');
  const [actionMessage, setActionMessage] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);

  useEffect(() => {
    fetchWallet();
  }, []);

  const fetchWallet = async () => {
    try {
      const res = await fetch(`${API_BASE_URL}/api/nextgen/wallet`, {
        headers: getAuthHeader(),
      });
      if (res.ok) setWallet(await res.json());
    } catch (err) {
      console.error('Failed to fetch wallet:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleDepositRazorpay = async (e) => {
    e.preventDefault();
    setActionMessage('');
    const amountNum = Number(depositAmount);
    if (!amountNum || amountNum < 10) {
      setActionMessage('⚠️ Minimum deposit amount is ₹10');
      return;
    }

    setIsProcessing(true);

    try {
      // 1. Create Razorpay Wallet Deposit Order
      const orderRes = await fetch(`${API_BASE_URL}/api/payments/wallet-order`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...getAuthHeader(),
        },
        body: JSON.stringify({ amount: amountNum }),
      });

      const orderData = await orderRes.json();
      if (!orderRes.ok) {
        throw new Error(orderData.message || 'Failed to initialize payment');
      }

      // 2. ALWAYS Open Razorpay Checkout Overlay Window
      const razorpayKey = orderData.keyId && orderData.keyId !== 'rzp_test_mockkey123'
        ? orderData.keyId
        : 'rzp_test_mockkey123';

      const options = {
        key: razorpayKey,
        amount: orderData.amount || amountNum * 100,
        currency: orderData.currency || 'INR',
        name: 'Arena-Verse eSports',
        description: `Arena Wallet Deposit - ₹${amountNum}`,
        image: '/images/logo-favicon.png',
        prefill: {
          name: user?.username || 'Competitor',
          email: user?.email || 'player@arenaverse.com',
          contact: '9999999999',
        },
        theme: {
          color: '#8b5cf6',
        },
        handler: async function (response) {
          try {
            setActionMessage('🔄 Verifying payment with Razorpay...');
            const verifyRes = await fetch(`${API_BASE_URL}/api/payments/verify-wallet-deposit`, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                ...getAuthHeader(),
              },
              body: JSON.stringify({
                amount: amountNum,
                razorpay_order_id: response.razorpay_order_id || orderData.orderId,
                razorpay_payment_id: response.razorpay_payment_id || `pay_${Date.now()}`,
                razorpay_signature: response.razorpay_signature || '',
              }),
            });

            const verifyData = await verifyRes.json();
            if (!verifyRes.ok) {
              throw new Error(verifyData.message || 'Payment verification failed');
            }

            setWallet(verifyData.wallet);
            setActionMessage(`🎉 Payment Verified! Successfully deposited ₹${amountNum} into your Arena Wallet.`);
          } catch (err) {
            setActionMessage(`⚠️ ${err.message}`);
          } finally {
            setIsProcessing(false);
          }
        },
        modal: {
          ondismiss: function () {
            setIsProcessing(false);
            setActionMessage('ℹ️ Deposit payment window was closed.');
          },
        },
      };

      // Attach real order_id if generated by Razorpay server
      if (!orderData.isMock && orderData.orderId && !orderData.orderId.startsWith('order_test_')) {
        options.order_id = orderData.orderId;
      }

      if (window.Razorpay) {
        const rzp = new window.Razorpay(options);
        rzp.on('payment.failed', function (response) {
          setIsProcessing(false);
          setActionMessage(`⚠️ Payment failed: ${response.error?.description || 'Transaction declined'}`);
        });
        rzp.open();
      } else {
        throw new Error('Razorpay SDK script not loaded on page. Please refresh and try again.');
      }
    } catch (err) {
      setActionMessage(`⚠️ ${err.message}`);
      setIsProcessing(false);
    }
  };

  const [payoutReceipt, setPayoutReceipt] = useState(null);

  const handleWithdraw = async (e) => {
    e.preventDefault();
    setActionMessage('');
    const amountNum = Number(withdrawAmount);

    if (!amountNum || amountNum < 50) {
      setActionMessage('⚠️ Minimum withdrawal amount is ₹50');
      return;
    }

    if (!upiId || !upiId.trim()) {
      setActionMessage('⚠️ Please enter a valid UPI ID (e.g. gamer@upi) or Bank Account details before requesting withdrawal.');
      return;
    }

    setIsProcessing(true);

    try {
      const res = await fetch(`${API_BASE_URL}/api/payments/initiate-withdrawal`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...getAuthHeader(),
        },
        body: JSON.stringify({ amount: amountNum, upiId: upiId.trim() }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.message);

      setWallet(data.wallet);
      setPayoutReceipt(data);
      setActionMessage(`🎉 Razorpay Payout Verified & Executed! ₹${amountNum} transferred to ${upiId.trim()}`);
    } catch (err) {
      setActionMessage(`⚠️ ${err.message}`);
    } finally {
      setIsProcessing(false);
    }
  };

  const handleQuickTopUp = async () => {
    setActionMessage('');
    try {
      const res = await fetch(`${API_BASE_URL}/api/payments/quick-topup`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...getAuthHeader(),
        },
        body: JSON.stringify({ amount: 1000 }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.message);
      setWallet(data.wallet);
      setActionMessage('🎉 Added ₹1,000 demo funds to your Arena Wallet!');
    } catch (err) {
      setActionMessage(`⚠️ ${err.message}`);
    }
  };

  if (loading) {
    return <div className="text-center py-5 mt-5"><p className="text-secondary text-sm">Loading Arena Wallet...</p></div>;
  }

  return (
    <div className="arena-wallet-page container py-4 mt-4">
      <div className="mb-4">
        <h1 className="section-title">Arena Wallet & Cash Management</h1>
        <p className="section-subtitle">Store tournament prize winnings, deposit funds via Razorpay / UPI for entry fees, and withdraw to bank or UPI via Razorpay Payouts.</p>
      </div>

      {actionMessage && (
        <div className="glass-panel p-3 mb-4 text-center font-bold text-sm" style={{ border: '1px solid rgba(139, 92, 246, 0.4)', borderRadius: '12px' }}>
          {actionMessage}
        </div>
      )}

      {/* Wallet Balance Card */}
      <div className="glass-panel p-4 mb-4" style={{ background: 'linear-gradient(135deg, rgba(139, 92, 246, 0.25), rgba(59, 130, 246, 0.25))', border: '1px solid rgba(139, 92, 246, 0.4)', borderRadius: '20px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
          <div>
            <p className="text-secondary text-xs font-bold uppercase m-0">Available Arena Balance</p>
            <h1 className="text-white font-extrabold m-0" style={{ fontSize: '2.8rem', letterSpacing: '0.02em' }}>
              ₹{(wallet?.balance || 0).toLocaleString('en-IN')}
            </h1>
            <p className="text-muted text-xs mt-1 m-0">Currency: {wallet?.currency || 'INR'} | Account: @{user?.username}</p>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <button 
              type="button" 
              className="btn btn-secondary btn-sm" 
              onClick={handleQuickTopUp}
              style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', fontSize: '0.8rem' }}
            >
              <Zap size={14} className="text-warning" /> Add ₹1,000 Demo Funds
            </button>
            <Wallet size={48} className="text-primary opacity-90" />
          </div>
        </div>
      </div>

      {/* Action Grid */}
      <div className="grid-2 gap-4 mb-4">
        <div className="glass-panel p-4" style={{ borderRadius: '16px' }}>
          <h3 className="text-white font-bold mb-3 flex items-center gap-2">
            <ArrowDownRight className="text-success" size={20} /> Deposit Funds via Razorpay / UPI
          </h3>

          <div className="mb-3">
            <label className="form-label text-xs text-secondary">Quick Amount Select</label>
            <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginTop: '4px' }}>
              {['100', '500', '1000', '2500', '5000'].map((amt) => (
                <button
                  key={amt}
                  type="button"
                  className={`btn btn-sm ${depositAmount === amt ? 'btn-primary' : 'btn-secondary'}`}
                  onClick={() => setDepositAmount(amt)}
                  style={{ borderRadius: '8px', fontSize: '0.8rem', padding: '4px 12px' }}
                >
                  +₹{amt}
                </button>
              ))}
            </div>
          </div>

          <form onSubmit={handleDepositRazorpay} className="flex-col gap-3">
            <div className="form-group">
              <label className="form-label">Custom Deposit Amount (₹)</label>
              <input
                type="number"
                className="form-control"
                value={depositAmount}
                onChange={e => setDepositAmount(e.target.value)}
                min={10}
                required
              />
            </div>
            <button type="submit" className="btn btn-primary w-full" disabled={isProcessing} style={{ gap: '8px' }}>
              <CreditCard size={16} />
              <span>{isProcessing ? 'Opening Razorpay...' : 'Pay & Deposit via Razorpay / UPI'}</span>
            </button>
          </form>
        </div>

        <div className="glass-panel p-4" style={{ borderRadius: '16px' }}>
          <h3 className="text-white font-bold mb-3 flex items-center gap-2">
            <ArrowUpRight className="text-warning" size={20} /> Withdraw Winnings via Razorpay Payouts
          </h3>
          <form onSubmit={handleWithdraw} className="flex-col gap-3">
            <div className="form-group">
              <label className="form-label">Withdraw Amount (₹)</label>
              <input
                type="number"
                className="form-control"
                value={withdrawAmount}
                onChange={e => setWithdrawAmount(e.target.value)}
                min={50}
                required
              />
            </div>
            <div className="form-group">
              <label className="form-label">Payout UPI ID / Bank A/C <span style={{ color: '#ef4444' }}>*</span></label>
              <input
                type="text"
                className="form-control"
                placeholder="e.g. gamer@upi or 123456789 (SBI)"
                value={upiId}
                onChange={e => setUpiId(e.target.value)}
                required
              />
            </div>
            <button type="submit" className="btn btn-warning w-full" disabled={isProcessing} style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}>
              <Zap size={16} />
              <span>{isProcessing ? 'Processing Payout...' : 'Request Instant Razorpay Payout'}</span>
            </button>
          </form>
        </div>
      </div>

      {/* Razorpay Payout Success Modal */}
      {payoutReceipt && (
        <div className="modal-backdrop" style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.85)', zIndex: 9999, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <div className="glass-panel p-5 text-center flex-col" style={{ width: '480px', maxWidth: '90vw', border: '1px solid rgba(16, 185, 129, 0.4)', borderRadius: '16px' }}>
            <div style={{ margin: '0 auto 12px auto', width: '56px', height: '56px', borderRadius: '50%', background: 'rgba(16, 185, 129, 0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <CheckCircle2 size={32} className="text-success" />
            </div>
            <h2 className="text-white font-extrabold text-lg mb-1">Razorpay Payout Executed!</h2>
            <p className="text-secondary text-xs mb-4">Instant cash withdrawal successfully processed via Razorpay Payouts API.</p>

            <div className="glass-panel p-3 mb-4 text-left flex-col gap-2" style={{ background: 'rgba(255,255,255,0.03)', borderRadius: '10px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px' }}>
                <span className="text-muted">Payout Amount:</span>
                <strong className="text-success">₹{payoutReceipt.amount}</strong>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px' }}>
                <span className="text-muted">Destination UPI / Bank:</span>
                <strong className="text-white">{payoutReceipt.upiId}</strong>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px' }}>
                <span className="text-muted">Razorpay Reference ID:</span>
                <strong className="text-warning" style={{ fontSize: '11px' }}>{payoutReceipt.payoutId}</strong>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px' }}>
                <span className="text-muted">Payout Gateway:</span>
                <span className="badge badge-published text-xs">RAZORPAY PAYOUTS</span>
              </div>
            </div>

            <button className="btn btn-primary w-full text-xs" onClick={() => setPayoutReceipt(null)}>
              Close Receipt
            </button>
          </div>
        </div>
      )}

      {/* Transaction History */}
      <div className="glass-panel p-4" style={{ borderRadius: '16px' }}>
        <h3 className="text-white font-bold mb-3 flex items-center gap-2">
          <ShieldCheck size={20} className="text-primary" /> Verified Wallet Transactions
        </h3>
        {!wallet?.transactions || wallet.transactions.length === 0 ? (
          <p className="text-muted text-center py-4">No wallet transactions recorded yet.</p>
        ) : (
          <div className="table-responsive">
            <table className="table" style={{ width: '100%', textAlign: 'left', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid rgba(255,255,255,0.1)', color: 'var(--text-muted)', fontSize: '0.8rem' }}>
                  <th style={{ padding: '10px' }}>Type</th>
                  <th style={{ padding: '10px' }}>Description</th>
                  <th style={{ padding: '10px' }}>Reference ID</th>
                  <th style={{ padding: '10px' }}>Amount</th>
                  <th style={{ padding: '10px' }}>Date</th>
                </tr>
              </thead>
              <tbody>
                {wallet.transactions.slice().reverse().map((txn, idx) => {
                  const isCredit = txn.type === 'deposit' || txn.type === 'prize_payout';
                  return (
                    <tr key={idx} style={{ borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                      <td style={{ padding: '10px' }}>
                        <span className={`badge ${isCredit ? 'badge-published' : 'badge-draft'}`} style={{ fontSize: '0.7rem' }}>
                          {txn.type.toUpperCase()}
                        </span>
                      </td>
                      <td style={{ padding: '10px' }} className="text-white text-xs">{txn.description}</td>
                      <td style={{ padding: '10px' }} className="text-secondary text-xs">{txn.referenceId || 'N/A'}</td>
                      <td style={{ padding: '10px' }} className={`font-bold ${isCredit ? 'text-success' : 'text-danger'}`}>
                        {isCredit ? '+' : '-'}₹{txn.amount}
                      </td>
                      <td style={{ padding: '10px' }} className="text-muted text-xs">
                        {new Date(txn.createdAt).toLocaleString('en-IN')}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};

export default ArenaWallet;

